package ShieldUIApp::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'ShieldUIApp::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:app.db',
        user => '',
        password => '',
    }
);

=head1 NAME

ShieldUIApp::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<ShieldUIApp>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<ShieldUIApp::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
